### ISSUE TITLE
Get error when running onComplete callback. Looks like the window.__coverage__ is not set.

### ISSUE THREAD

**Issue by sandipchitale** [edvlucas/angular-e2e-coverage#2]
BTW I created my own project using `ng new` with Angular CLI 9.x

Get the following exception in onComplete() callback. Is something missing in the instructions so that the code will get instrumented?

I did ```npm install istanbul --save-dev``` . I think need the instructions on how to enable the coverage. 

```
E2E finished - retrieving coverage from browser
[13:14:48] E/launcher - Cannot read property 'length' of null
[13:14:48] E/launcher - TypeError: Cannot read property 'length' of null
    at ...\e2ecoverageroot\e2ecoverage\e2e\protractor.conf.js:35:66
    at ManagedPromise.invokeCallback_ (...\e2ecoverageroot\e2ecoverage\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (...\e2ecoverageroot\e2ecoverage\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (...\e2ecoverageroot\e2ecoverage\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at ...\e2ecoverageroot\e2ecoverage\node_modules\selenium-webdriver\lib\promise.js:2927:27
    at ...\e2ecoverageroot\e2ecoverage\node_modules\selenium-webdriver\lib\promise.js:668:7
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
My app info:

```
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.5
Node: 12.16.1
OS: win32 x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.5
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by sandipchitale** [comment]
I figured out the issue. I had to instrument the code. This can be closed.
